server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          filters[0]: PreserveHostHeader   #支持注册服务可以具有根路径
          enabled: true
          lower-case-service-id: true
      routes:
        - id: shopp-service-route
          uri: lb://shopp-service
          predicates:
            - Path=/shopp-service/**
          filters:
            - StripPrefix= 1
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG