server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: open
          uri: lb://open
          predicates:
            - Path=/open/**
          filters:
            - StripPrefix= 1
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix= 1