server:
  port: 10001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seamzhou/spring-config
          #uri: https://github.com/huzhicheng/config-only-a-demo
          username: adanmint@163.com
          password: zhouwenjun123
          default-label: master
          search-paths: config-demo