server:
  port: 10003
  servlet:
    context-path: /shopp-service

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: bootstrap.yml