server:
  port: 10002
  servlet:
    context-path: /user-service

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  config:
    import: bootstrap.yml

